version: '3'

vars:
    TARGET_FOLDER: build

    SOURCE_FOLDER:
        sh: find . -regex ".*\.go$" | head -n 1 | grep -Po ".*(?=\/)"

    AUTHOR:
        sh: grep -Po "(?<=name\s=\s).*" ~/.gitconfig

    APP_NAME:
        sh: pwd | tr '/' '\n' | tail -1

    ARCH:
        sh: arch

    DATE:
        sh: date

    GIT_COMMIT_NO:
        sh: git rev-list --all --count

    GIT_COMMIT_HASH:
        sh: git rev-parse HEAD

tasks:
    default:
        cmds:
            - task: build

    build: >-
            bob -b V -c
            -l '_subversion: {{.GIT_COMMIT_NO}}, Author: {{.AUTHOR}},
            Build date: {{.DATE}}, Git hash: {{.GIT_COMMIT_HASH}}'

    test:
        cmds:
            - cmd: go test -cover -bench=. {{.SOURCE_FOLDER}}/*.go
