retrieval_urls = [
  "https://api.ip.sb/ip",
  "http://icanhazip.com",
  "https://ident.me",
  "http://ipecho.net/plain",
  "http://plain-text-ip.com",
  "https://api.ipify.org?format=text",
  "https://wtfismyip.com/text",
  "https://jsonip.com",
]

[[dynamic_name_services]]
method = "get"
url = "http://anydnsservice.com?user={{.hostname}}&pass={{.token}}&hostname={{.hostname}}&myip={{.ip}}"
hostname = "my_hostname"
token = "my_token"
